version: '3'
services:
  db:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: graphql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080
  graphql:
    build: .
    volumes: 
      - ./src:/graphql/src
    ports:
      - 4000:4000
    command: bash -c "cd src && node server"
    depends_on: 
      - db
    

# cd src && npx knex migrate:latest